/* tslint:disable */
/* eslint-disable */
/*
Svix API

Welcome to the Svix API documentation!

Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)

# Introduction

This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).

## Main concepts

In Svix you have four important entities you will be interacting with:

- `messages`: these are the webhooks being sent. They can have contents and a few other properties.
- `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.
- `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).
- `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.


## Authentication

Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).




## Code samples

The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).


## Idempotency

Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.

To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions.

Svix's idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.

Please note that idempotency is only supported for `POST` requests.


## Cross-Origin Resource Sharing

This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.


The version of the OpenAPI document: 1.21.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BackgroundTaskOut } from '../models';
// @ts-ignore
import { BackgroundTaskStatus } from '../models';
// @ts-ignore
import { BackgroundTaskType } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { HttpErrorOut } from '../models';
// @ts-ignore
import { ListResponseBackgroundTaskOut } from '../models';
// @ts-ignore
import { Ordering } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * BackgroundTasksApi - axios parameter creator
 * @export
 */
export const BackgroundTasksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a background task by ID.
         * @summary Get Background Task
         * @param {string} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (taskId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getById', 'taskId', taskId)
            const localVarPath = `/api/v1/background-task/{task_id}`
                .replace(`{${"task_id"}}`, encodeURIComponent(String(taskId !== undefined ? taskId : `-task_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/background-task/{task_id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List background tasks executed in the past 90 days.
         * @summary List Background Tasks
         * @param {BackgroundTaskStatus} [status] Filter the response based on the status
         * @param {BackgroundTaskType} [task] Filter the response based on the type
         * @param {number} [limit] Limit the number of returned items
         * @param {string} [iterator] The iterator returned from a prior invocation
         * @param {Ordering} [order] The sorting order of the returned items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPastTasks: async (status?: BackgroundTaskStatus, task?: BackgroundTaskType, limit?: number, iterator?: string, order?: Ordering, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/background-task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (task !== undefined) {
                localVarQueryParameter['task'] = task;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (iterator !== undefined) {
                localVarQueryParameter['iterator'] = iterator;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/background-task',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BackgroundTasksApi - functional programming interface
 * @export
 */
export const BackgroundTasksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BackgroundTasksApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a background task by ID.
         * @summary Get Background Task
         * @param {BackgroundTasksApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: BackgroundTasksApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BackgroundTaskOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.taskId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List background tasks executed in the past 90 days.
         * @summary List Background Tasks
         * @param {BackgroundTasksApiGetPastTasksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPastTasks(requestParameters: BackgroundTasksApiGetPastTasksRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListResponseBackgroundTaskOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPastTasks(requestParameters.status, requestParameters.task, requestParameters.limit, requestParameters.iterator, requestParameters.order, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BackgroundTasksApi - factory interface
 * @export
 */
export const BackgroundTasksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BackgroundTasksApiFp(configuration)
    return {
        /**
         * Get a background task by ID.
         * @summary Get Background Task
         * @param {BackgroundTasksApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: BackgroundTasksApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<BackgroundTaskOut> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * List background tasks executed in the past 90 days.
         * @summary List Background Tasks
         * @param {BackgroundTasksApiGetPastTasksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPastTasks(requestParameters: BackgroundTasksApiGetPastTasksRequest = {}, options?: AxiosRequestConfig): AxiosPromise<ListResponseBackgroundTaskOut> {
            return localVarFp.getPastTasks(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getById operation in BackgroundTasksApi.
 * @export
 * @interface BackgroundTasksApiGetByIdRequest
 */
export type BackgroundTasksApiGetByIdRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof BackgroundTasksApiGetById
    */
    readonly taskId: string
    
}

/**
 * Request parameters for getPastTasks operation in BackgroundTasksApi.
 * @export
 * @interface BackgroundTasksApiGetPastTasksRequest
 */
export type BackgroundTasksApiGetPastTasksRequest = {
    
    /**
    * Filter the response based on the status
    * @type {BackgroundTaskStatus}
    * @memberof BackgroundTasksApiGetPastTasks
    */
    readonly status?: BackgroundTaskStatus
    
    /**
    * Filter the response based on the type
    * @type {BackgroundTaskType}
    * @memberof BackgroundTasksApiGetPastTasks
    */
    readonly task?: BackgroundTaskType
    
    /**
    * Limit the number of returned items
    * @type {number}
    * @memberof BackgroundTasksApiGetPastTasks
    */
    readonly limit?: number
    
    /**
    * The iterator returned from a prior invocation
    * @type {string}
    * @memberof BackgroundTasksApiGetPastTasks
    */
    readonly iterator?: string
    
    /**
    * The sorting order of the returned items
    * @type {Ordering}
    * @memberof BackgroundTasksApiGetPastTasks
    */
    readonly order?: Ordering
    
}

/**
 * BackgroundTasksApiGenerated - object-oriented interface
 * @export
 * @class BackgroundTasksApiGenerated
 * @extends {BaseAPI}
 */
export class BackgroundTasksApiGenerated extends BaseAPI {
    /**
     * Get a background task by ID.
     * @summary Get Background Task
     * @param {BackgroundTasksApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackgroundTasksApiGenerated
     */
    public getById(requestParameters: BackgroundTasksApiGetByIdRequest, options?: AxiosRequestConfig) {
        return BackgroundTasksApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List background tasks executed in the past 90 days.
     * @summary List Background Tasks
     * @param {BackgroundTasksApiGetPastTasksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackgroundTasksApiGenerated
     */
    public getPastTasks(requestParameters: BackgroundTasksApiGetPastTasksRequest = {}, options?: AxiosRequestConfig) {
        return BackgroundTasksApiFp(this.configuration).getPastTasks(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
